/** PocketBase collection names (sabok_ prefix). */
export const C = {
  tenants: "sabok_tenants",
  users: "sabok_users",
  userTenants: "sabok_user_tenants",
  companySettings: "sabok_company_settings",
  employees: "sabok_employees",
  levelPaymentRules: "sabok_level_payment_rules",
  level5Overrides: "sabok_level5_overrides",
  levelTargets: "sabok_level_targets",
  quarterlyRates: "sabok_quarterly_rates",
  quarterlyEmployeeConfigs: "sabok_quarterly_employee_configs",
  monthlyEmployeeNotes: "sabok_monthly_employee_notes",
  monthlyPaymentStatus: "sabok_monthly_payment_status",
  auditLogs: "sabok_audit_logs",
  glSyncJobs: "sabok_gl_sync_jobs",
  vendors: "sabok_vendors",
  vendorContributions: "sabok_vendor_contributions",
  baseAssetAnnual: "sabok_base_asset_annual",
  fundOperationAnnual: "sabok_fund_operation_annual",
  fundSourceAnnual: "sabok_fund_source_annual",
  contribUsageAnnual: "sabok_contrib_usage_annual",
  bizResultAnnual: "sabok_biz_result_annual",
  realEstateHoldings: "sabok_real_estate_holdings",
} as const;
